### ISSUE TITLE
tagging version for reuse

### ISSUE THREAD

**Issue by gasolin** [buildingfirefoxos/Building-Blocks#16]
Please consider have tags such as `v1.3.x`, the first 2 digits correspondent to Firefox OS main version, the third is for Building-Blocks.

There're 2 related issues fired under mozilla-b2g/Gaia-UI-Building-Blocks:
- Project should start using git tags https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/issues/68
- make Building-Blocks bower installable https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/issues/76

And would you consider delete that unmaintained repository?

**Comment by gasolin** [comment]
needinfo @rnowm

**Comment by rnowm** [comment]
@gasolin +1 to tag BB. But I guess we should be doing this in gaia/shared, as this repo is fetching from there.
What maybe we could use this repo for is to make the bower installable version.
Do you want me to add you as collaborator (or anybody in your team) to work on that here?
I'm not an expert in bower :)

**Comment by gasolin** [comment]
I'm using my spare time to do this too. Please add me as collaborator if you feel appropriate.

I think to tag gaia/shared/ to different version is not possible for a certain time, It's better to let BB easily available for web developers, then we can try to delegate the gaia/shared/style to this repository.

**Comment by rnowm** [comment]
Cool! Feel free to do any improvement you want to :)

**Comment by gasolin** [comment]
tagging as 1.3.1 (since it comes from gaia master and 1.4 is not branched yet).

now it's able to run 'bower install building-blocks' command to get BB :dancer:
