### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by acuster** [buildingfirefoxos/Building-Blocks#20]
The project name "Building Firefox OS" is completely misleading since the project has nothing to do with building the operating system but rather is about building _Apps_ for Firefox OS.

**Comment by rnowm** [comment]
At this stage I will not change the domain name :)
In fact I'm building Firefox OS, and I created buildingfirefoxos.com to provide documentation about Building Blocks and transitions to my colleagues working in the OS.
But thanks for pointing that out.
