### ISSUE TITLE
Provide a point of contact

### ISSUE THREAD

**Issue by acuster** [buildingfirefoxos/Building-Blocks#21]
Your work, and the general confusion over styling and app resources for Firefox OS, raises many questions. 

Neither the web site nor the GitHub repo provide any indication of where conversations, questions, and discussion of this work should take place. It would be useful to have that information both in the Readme.md of the GitHub site and on the website.

**Comment by rnowm** [comment]
I am the contact person, so is the rest of Firefox OS community as this is an open source project.
And GH Issues is a good place to start conversations.
And also dev-gaia mailing list: dev-gaia@lists.mozilla.org
I will update the readme.
Thanks

**Comment by rnowm** [comment]
Hope the updated readme helps understand better the meaning if this repo ;)
