### ISSUE TITLE
Web site should explain its relation to Mozilla.org/com

### ISSUE THREAD

**Issue by acuster** [buildingfirefoxos/Building-Blocks#22]
The web site is in a separate domain 'buildingfirefoxos.com". However, it has a Mozilla style header. Is the web site related to Mozilla? Is it a Mozilla project? 

The web site should explain the relation of the project to Mozilla.

**Comment by rnowm** [comment]
I created buildingfirefoxos.com together with @sergivila as a personal project.
Then Mozilla offered us to use the official branding for the site.
You could read the full story here:
https://hacks.mozilla.org/2013/07/firefox-os-building-blocks-find-a-new-home-and-get-more-streamlined/
