### ISSUE TITLE
Clarify the audience(s) for your site

### ISSUE THREAD

**Issue by acuster** [buildingfirefoxos/Building-Blocks#24]
The Building Blocks section of the site seems to be for App developers, probably primarily Gaia developers (is the default color scheme intended only for more merely required of Gaia apps?) but possibly also third party developers.

The Transtions section of the site seems mostly geared at the design of the main app since most transtions are out of the hands of developers of regular Apps. The situation is confusing, making readers wonder who the target audience might be.

The Download section of the site includes access to the Font file something that is presumably installed on all devices and should therefore _not_ be used by App developers. 

So presumably this site is acting in several different roles for several different audiences. That needs to be clarified in general and specified explicitly when a section only targets a certain group.

**Comment by rnowm** [comment]
You are right again.
buildingfirefoxos.com was initially meant to help gaia developers, as you noticed in system transitions.
But of course that does not mean it could help the rest of the community.
About the font, we also wanted to help visual designers create their own apps. They will need the system font installed to do that.
