### ISSUE TITLE
Provide SVG icons

### ISSUE THREAD

**Issue by acuster** [buildingfirefoxos/Building-Blocks#25]
The icon images are supposedly in a vector format in the original photoshop source. It should therefore be relatively easy to provide SVG versions of the icons. Vector format icons are needed when these icons are used at larger sizes.

**Comment by rnowm** [comment]
Sure, we first need to deal with performance issues before we move to SVGs in Firefox OS. We are pushing in that direction.

@acuster thanks for all your comments!
