### ISSUE TITLE
Header search

### ISSUE THREAD

**Issue by ripper2hl** [buildingfirefoxos/Building-Blocks#58]
The head is wrongly positioned.

![captura el 2014-11-02 a las 00 07 42](https://cloud.githubusercontent.com/assets/2611201/4879020/e10de824-631f-11e4-901b-61eef95889e8.png)

**Comment by rnowm** [comment]
You need to link https://github.com/mozilla-b2g/gaia/blob/master/shared/js/font_size_utils.js in your app in order to get the header title centered.
Input fields inside the header are discontinued in FirefoxOS :(

**Comment by ripper2hl** [comment]
thanks for the information, bbs is a great project and should create a simple migration guide for gaia-components :+1: 

my english is very bad xD
