### ISSUE TITLE
Update Building Blocks to pass the Content Security Policy of Firefox Marketplace

### ISSUE THREAD

**Issue by juaneladio** [buildingfirefoxos/Building-Blocks#7]
Steps to reproduce: Create a zip file with the repository contents, update to the Validator in Firefox Marketplace and check the results:

Now it shows some messages "CSP Violation Detected" because there is <script> tags inside HTML pages, JavaScript code in forms (onsubmit="return false;") and setTimeout (although this one is only because they want a function as a parameter and the parser can't distinguish between Javascript functions or strings).

It think is important to check these messages because many people are using the Building Blocks and then discovers there are 'violations' caused by Building Blocks elements.

**Comment by gasolin** [comment]
seems fixed
