### ISSUE TITLE
Small fix in markup (style_unstable/tabs/index.html)

### ISSUE THREAD

**Issue by juaneladio** [buildingfirefoxos/Building-Blocks#8]
While running the Validator in the Firefox Marketplace it showed this warning:

Markup parsing error

Warning: The markup file has more closing tags than it has opening tags.
style_unstable/tabs/index.html
74 </body>
75 </html>

**Comment by rnowm** [comment]
@nucliweb did a W3C markup validation some weeks ago, I think that has been addressed.
Thanks @juaneladio.
