### ISSUE TITLE
Add that you need "seekbars.js" to the documentation

### ISSUE THREAD

**Issue by aarondruck** [buildingfirefoxos/Building-Blocks#9]
On the docs page here:
http://buildingfirefoxos.com/building-blocks/seek-bars.html

There should be a note to add in seekbars.js in your app as well.

**Comment by rnowm** [comment]
Thanks @aarondruck.
BB are just HTML and CSS, some colleagues at work created extra functionality for seekbars as you mentioned.
This is not officially supported in Firefox OS repo (https://github.com/mozilla-b2g/gaia). So I prefer having this code in the BB demo app only, by now ;)
